# Bash settings
set -o vi
export EDITOR=/usr/bin/vim
bind -m vi-insert "\C-l":clear-screen
bind -x '"\C-o": "ranger"'
bind '"\C-j": history-search-forward'
bind '"\C-k": history-search-backward'
alias ls='ls --color -h --group-directories-first'
alias gm='cd $HOME/Music'
alias gd='cd $HOME/Downloads'
# alias lst='lsd --group-dirs --tree --color never'
# alias ll='lsd --group-dirs -l --color never'
# alias ranger="python3 $HOME/workspace/ranger/ranger.py"
# Move to the directory when exiting.
# alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR";'
alias bashrc="vim ${BASH_SOURCE[0]} -c 'normal zt'"
alias vimrc="vim $HOME/.vimrc"
alias dmenuconfig="vim $HOME/workspace/dmenu/config.h"
alias stconfig="vim $HOME/workspace/st/config.h"
alias loginwallpaper="sudo vim +/#lockDialogGroup /usr/share/gnome-shell/theme/ubuntu.css"
alias sxiv='sxiv -a -f'
alias screen='bash $HOME/workspace/ubuntu-fresh/screen.sh'

# Tmux
if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
	exec tmux
fi

# Powerline-status
PATH="$HOME/.local/bin:$PATH"
export POWERLINE_COMMAND=powerline
if [ -f ~/.local/lib/python3*/site-packages/powerline/bindings/bash/powerline.sh ]; then
	source ~/.local/lib/python3*/site-packages/powerline/bindings/bash/powerline.sh
fi

