#!/usr/bin/env bash

bspc monitor HDMI-1 -d "1" "2" "3" "4" "5" "6" "7"
bspc monitor eDP-1 -d "1" "2" "3" "4" "5" "6" "7"

bspc config border_width			1
bspc config top_padding				24
bspc config window_gap				12
bspc config split_ratio				0.52
bspc config borderless_monocle		false
bspc config gapless_monocle			false
bspc config click_to_focus			true
bspc config focus_follows_pointer	true

# bar
bspc rule -a "polybar" state=sticky

# floating applications
bspc rule -a "stacer" desktop='^1' state=floating center=on follow=on focus=on border=off
bspc rule -a "Lxappearance" desktop='^1' state=floating center=on follow=on focus=on
bspc rule -a "Blueman-manager" desktop='^1' state=floating center=on follow=on focus=on
bspc rule -a "Transmission-gtk" desktop='^1' state=floating center=on follow=on focus=on
bspc rule -a "Nm-connection-editor" desktop='^1' state=floating center=on follow=on focus=on
bspc rule -a "Org.gnome.Nautilus" desktop='^1' state=floating center=on follow=on focus=on
bspc rule -a "obs" desktop='^1' state=floating center=on follow=on focus=on
bspc rule -a "Plank" layer=above manage=on border=off

bspc rule -a "st-256color" desktop='^2' follow=on focus=on
bspc rule -a "Firefox" state=monocle follow=on focus=on
bspc rule -a "Firefox:Places" state=floating follow=on focus=on border=off
bspc rule -a "Firefox:Dialog" state=floating follow=on focus=on border=off
bspc rule -a "Firefox:Alert" state=floating follow=on focus=on border=off
bspc rule -a "Vlc" desktop='^4' follow=on
bspc rule -a "Steam" desktop='^5' state=floating follow=on focus=on border=off
bspc rule -a "vlc" desktop='^6' center=on follow=on state=floating

bspc rule -a "Wine" desktop='^7' follow=on focus=on state=floating border=off
bspc rule -a "Wine:leagueclient" desktop='^7' follow=on focus=on state=floating border=off
bspc rule -a "Wine:leagueclientux.exe" desktop='^7' follown=on focus=on state=floating border=off

bspc desktop '^3' -l monocle
bspc desktop '^4' -l monocle

fd1=$(bspc query -D -d '^1')
fd2=$(bspc query -D -d '^5')
bspc subscribe node | while read -a msg ; do
	desk_id=${msg[2]}
	wid=${msg[3]}
	if [ "$desk_id" = "$fd1" ] || [ "$desk_id" = "$fd2" ]; then
		bspc node "$wid" -t floating
	fi
done

