git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse

keybinding:
  universal:
    quit-alt1: '<esc>' 
    return: '<C-c>'
