[keyboard]
bindings = [
    # <C-,> = <C-p>a
    # <C-.> = <C-p>b
    # <C-/> = <C-p>c
    # <C-;> = <C-p>d
    # {key = "Period", mods = "Control", chars = "\u001B[44;5u"},
    # {key = "Comma", mods = "Control", chars = "\u001B[46;5u"},
    # {key = "Slash", mods = "Control", chars = "\u001B[47;5u"},
    # {key = "Semicolon", mods = "Control", chars = "\u001B[59;5u"},
    # <C-,> = <C-q>a
    # <C-.> = <C-q>b
    # <C-/> = <C-q>c
    # <C-;> = <C-q>d
    {key = "Comma", mods = "Control", chars = "\u0011a"},
    {key = "Period", mods = "Control", chars = "\u0011b"},
    {key = "Slash", mods = "Control", chars = "\u0011c"},
    {key = "Semicolon", mods = "Control", chars = "\u0011d"},
    #
    {key = "Key0", mods = "Alt", chars = "\u001B0"},
    {key = "Key1", mods = "Alt", chars = "\u001B1"},
    {key = "Key2", mods = "Alt", chars = "\u001B2"},
    {key = "Key3", mods = "Alt", chars = "\u001B3"},
    {key = "Key4", mods = "Alt", chars = "\u001B4"},
    {key = "Key5", mods = "Alt", chars = "\u001B5"},
    {key = "Key6", mods = "Alt", chars = "\u001B6"},
    {key = "Key7", mods = "Alt", chars = "\u001B7"},
    {key = "Key8", mods = "Alt", chars = "\u001B8"},
    {key = "Key9", mods = "Alt", chars = "\u001B9"},
    {key = "Key0", mods = "Control", chars = "\u00170"},
    {key = "Key1", mods = "Control", chars = "\u00171"},
    {key = "Key2", mods = "Control", chars = "\u00172"},
    {key = "Key3", mods = "Control", chars = "\u00173"},
    {key = "Key4", mods = "Control", chars = "\u00174"},
    {key = "Key5", mods = "Control", chars = "\u00175"},
    {key = "Key6", mods = "Control", chars = "\u00176"},
    {key = "Key7", mods = "Control", chars = "\u00177"},
    {key = "Key8", mods = "Control", chars = "\u00178"},
    {key = "Key9", mods = "Control", chars = "\u00179"},
    {key = "Paste", action = "Paste"},
    {key = "Copy", action = "Copy"},
    {key = "L", mods = "Control", action = "ClearLogNotice"},
    {key = "L", mods = "Control", chars = "\f"},
    {key = "Home", mods = "Alt", chars = "\u001B[1;3H"},
    {key = "Home", mode = "AppCursor", chars = "\u001BOH"},
    {key = "Home", mode = "~AppCursor", chars = "\u001B[H"},
    {key = "End", mods = "Alt", chars = "\u001B[1;3F"},
    {key = "End", mode = "AppCursor", chars = "\u001BOF"},
    {key = "End", mode = "~AppCursor", chars = "\u001B[F"},
    {key = "PageUp", mode = "~Alt", action = "ScrollPageUp", mods = "Shift"},
    {key = "PageUp", mode = "Alt", chars = "\u001B[5;2~", mods = "Shift"},
    {key = "PageUp", mods = "Control", chars = "\u001B[5;5~"},
    {key = "PageUp", mods = "Alt", chars = "\u001B[5;3~"},
    {chars = "\u001B[5~", key = "PageUp"},
    {action = "ScrollPageDown", key = "PageDown", mode = "~Alt", mods = "Shift"},
    {chars = "\u001B[6;2~", key = "PageDown", mode = "Alt", mods = "Shift"},
    {chars = "\u001B[6;5~", key = "PageDown", mods = "Control"},
    {chars = "\u001B[6;3~", key = "PageDown", mods = "Alt"},
    {chars = "\u001B[6~", key = "PageDown"},
    {chars = "\u001B[Z", key = "Tab", mods = "Shift"},
    {chars = "\u007F", key = "Back"},
    {chars = "\u001B\u007F", key = "Back", mods = "Alt"},
    {chars = "\u001B[2~", key = "Insert"},
    {chars = "\u001B[3~", key = "Delete"},
    {chars = "\u001B[1;2D", key = "Left", mods = "Shift"},
    {chars = "\u001B[1;5D", key = "Left", mods = "Control"},
    {chars = "\u001B[1;3D", key = "Left", mods = "Alt"},
    {chars = "\u001B[D", key = "Left", mode = "~AppCursor"},
    {chars = "\u001BOD", key = "Left", mode = "AppCursor"},
    {chars = "\u001B[1;2C", key = "Right", mods = "Shift"},
    {chars = "\u001B[1;5C", key = "Right", mods = "Control"},
    {chars = "\u001B[1;3C", key = "Right", mods = "Alt"},
    {chars = "\u001B[C", key = "Right", mode = "~AppCursor"},
    {chars = "\u001BOC", key = "Right", mode = "AppCursor"},
    {chars = "\u001B[1;2A", key = "Up", mods = "Shift"},
    {chars = "\u001B[1;5A", key = "Up", mods = "Control"},
    {chars = "\u001B[1;3A", key = "Up", mods = "Alt"},
    {chars = "\u001B[A", key = "Up", mode = "~AppCursor"},
    {chars = "\u001BOA", key = "Up", mode = "AppCursor"},
    {chars = "\u001B[1;2B", key = "Down", mods = "Shift"},
    {chars = "\u001B[1;5B", key = "Down", mods = "Control"},
    {chars = "\u001B[1;3B", key = "Down", mods = "Alt"},
    {chars = "\u001B[B", key = "Down", mode = "~AppCursor"},
    {chars = "\u001BOB", key = "Down", mode = "AppCursor"},
    {chars = "\u001BOP", key = "F1"},
    {chars = "\u001BOQ", key = "F2"},
    {chars = "\u001BOR", key = "F3"},
    {chars = "\u001BOS", key = "F4"},
    {chars = "\u001B[15~", key = "F5"},
    {chars = "\u001B[17~", key = "F6"},
    {chars = "\u001B[18~", key = "F7"},
    {chars = "\u001B[19~", key = "F8"},
    {chars = "\u001B[20~", key = "F9"},
    {chars = "\u001B[21~", key = "F10"},
    {chars = "\u001B[23~", key = "F11"},
    {chars = "\u001B[24~", key = "F12"},
    {chars = "\u001B[1;2P", key = "F1", mods = "Shift"},
    {chars = "\u001B[1;2Q", key = "F2", mods = "Shift"},
    {chars = "\u001B[1;2R", key = "F3", mods = "Shift"},
    {chars = "\u001B[1;2S", key = "F4", mods = "Shift"},
    {chars = "\u001B[15;2~", key = "F5", mods = "Shift"},
    {chars = "\u001B[17;2~", key = "F6", mods = "Shift"},
    {chars = "\u001B[18;2~", key = "F7", mods = "Shift"},
    {chars = "\u001B[19;2~", key = "F8", mods = "Shift"},
    {chars = "\u001B[20;2~", key = "F9", mods = "Shift"},
    {chars = "\u001B[21;2~", key = "F10", mods = "Shift"},
    {chars = "\u001B[23;2~", key = "F11", mods = "Shift"},
    {chars = "\u001B[24;2~", key = "F12", mods = "Shift"},
    {chars = "\u001B[1;5P", key = "F1", mods = "Control"},
    {chars = "\u001B[1;5Q", key = "F2", mods = "Control"},
    {chars = "\u001B[1;5R", key = "F3", mods = "Control"},
    {chars = "\u001B[1;5S", key = "F4", mods = "Control"},
    {chars = "\u001B[15;5~", key = "F5", mods = "Control"},
    {chars = "\u001B[17;5~", key = "F6", mods = "Control"},
    {chars = "\u001B[18;5~", key = "F7", mods = "Control"},
    {chars = "\u001B[19;5~", key = "F8", mods = "Control"},
    {chars = "\u001B[20;5~", key = "F9", mods = "Control"},
    {chars = "\u001B[21;5~", key = "F10", mods = "Control"},
    {chars = "\u001B[23;5~", key = "F11", mods = "Control"},
    {chars = "\u001B[24;5~", key = "F12", mods = "Control"},
    {chars = "\u001B[1;6P", key = "F1", mods = "Alt"},
    {chars = "\u001B[1;6Q", key = "F2", mods = "Alt"},
    {chars = "\u001B[1;6R", key = "F3", mods = "Alt"},
    {chars = "\u001B[1;6S", key = "F4", mods = "Alt"},
    {chars = "\u001B[15;6~", key = "F5", mods = "Alt"},
    {chars = "\u001B[17;6~", key = "F6", mods = "Alt"},
    {chars = "\u001B[18;6~", key = "F7", mods = "Alt"},
    {chars = "\u001B[19;6~", key = "F8", mods = "Alt"},
    {chars = "\u001B[20;6~", key = "F9", mods = "Alt"},
    {chars = "\u001B[21;6~", key = "F10", mods = "Alt"},
    {chars = "\u001B[23;6~", key = "F11", mods = "Alt"},
    {chars = "\u001B[24;6~", key = "F12", mods = "Alt"},
    {chars = "\u001B[1;3P", key = "F1", mods = "Super"},
    {chars = "\u001B[1;3Q", key = "F2", mods = "Super"},
    {chars = "\u001B[1;3R", key = "F3", mods = "Super"},
    {chars = "\u001B[1;3S", key = "F4", mods = "Super"},
    {chars = "\u001B[15;3~", key = "F5", mods = "Super"},
    {chars = "\u001B[17;3~", key = "F6", mods = "Super"},
    {chars = "\u001B[18;3~", key = "F7", mods = "Super"},
    {chars = "\u001B[19;3~", key = "F8", mods = "Super"},
    {chars = "\u001B[20;3~", key = "F9", mods = "Super"},
    {chars = "\u001B[21;3~", key = "F10", mods = "Super"},
    {chars = "\u001B[23;3~", key = "F11", mods = "Super"},
    {chars = "\u001B[24;3~", key = "F12", mods = "Super"},
    {chars = """ """, key =  "NumpadEnter"}
]
