[schemes.gruvbox_dark.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[schemes.gruvbox_dark.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[schemes.gruvbox_light.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[schemes.gruvbox_light.normal]
black = "0xfbf1c7"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0x7c6f64"
yellow = "0xd79921"

[schemes.gruvbox_light.primary]
background = "0xfbf1c7"
foreground = "0x3c3836"

[schemes.material.bright]
black = "0xff262b"
blue = "0x7dc6bf"
cyan = "0x35434d"
green = "0xc3e88d"
magenta = "0x6c71c4"
red = "0xeb606b"
white = "0xffffff"
yellow = "0xf7eb95"

[schemes.material.normal]
black = "0x666666"
blue = "0x80cbc4"
cyan = "0xaeddff"
green = "0xc3e88d"
magenta = "0xff2f90"
red = "0xeb606b"
white = "0xffffff"
yellow = "0xf7eb95"

[schemes.material.primary]
background = "0x1e282d"
foreground = "0xc4c7d1"

[schemes.nord.colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[schemes.nord.colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[schemes.nord.colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[schemes.nord.colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[schemes.nord.colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[schemes.nord.colors.search.bar]
background = "#434c5e"
foreground = "#d8dee9"

[schemes.nord.colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[schemes.nord.colors.selection]
background = "#4c566a"
text = "CellForeground"

[schemes.nord.colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[[schemes.one_dark.indexed_colors]]
color = "0xd19a66"
index = 16

[[schemes.one_dark.indexed_colors]]
color = "0xf65866"
index = 17

[schemes.one_dark.bright]
black = "0x21252b"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe86671"
white = "0xabb2bf"
yellow = "0xe0af68"

[schemes.one_dark.normal]
black = "0x20232A"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe86671"
white = "0x798294"
yellow = "0xe0af68"

[schemes.one_dark.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[schemes.solarized_dark.cursor]
cursor = "0x839496"
text = "0x002b36"

[schemes.solarized_dark.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[schemes.solarized_dark.primary]
background = "0x002b36"
foreground = "0x839496"

[schemes.solarized_light.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[schemes.solarized_light.cursor]
cursor = "0x657b83"
text = "0xfdf6e3"

[schemes.solarized_light.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[schemes.solarized_light.primary]
background = "0xfdf6e3"
foreground = "0x657b83"


