.phony:
	cargo fcitx fonts fresh fzf git \
		lazygit lg lazy icons nvim neovim plank ranger rofi \
		shell tmux youtube-dl youtube yt vlc xow zsh

cargo:
	@./main.sh "cargo"

fcitx:
	@./main.sh "fcitx"

fonts:
	@./main.sh "fonts"

fresh:
	@./main.sh "fresh"

fzf:
	@./main.sh "fzf"

git:
	@./main.sh "git"

lazygit lg lazy:
	@./main.sh "lazygit"

nvim neovim:
	@./main.sh "nvim"

plank:
	@./main.sh "plank"

ranger:
	@./main.sh "ranger"

rofi:
	@./main.sh "rofi"

shell:
	@./main.sh "shell"

tmux:
	@./main.sh "tmux"

youtube-dl youtube yt:
	@./main.sh "youtube"

vlc:
	@./main.sh "vlc"

xow:
	@./main.sh "xow"

zsh:
	@./main.sh "zsh"
