.PHONY: cargo fcitx fonts fresh fzf \
		icons nvim neovim plank ranger \
		shell youtube-dl youtube yt vlc xow zsh

cargo:
	@./main.sh "cargo"

fcitx:
	@./main.sh "fcitx"

fonts:
	@./main.sh "fonts"

fresh:
	@./main.sh "fresh"

fzf:
	@./main.sh "fzf"

nvim neovim:
	@./main.sh "nvim"

plank:
	@./main.sh "plank"

ranger:
	@./main.sh "ranger"

shell:
	@./main.sh "shell"

streamlink:
	@./main.sh "streamlink"

youtube-dl youtube yt:
	@./main.sh "youtube"

vlc:
	@./main.sh "vlc"

xow:
	@./main.sh "xow"

zsh:
	@./main.sh "zsh"
