#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d "1" "2" "3" "4" "5" "6" "7"

bspc config border_width			  2
bspc config normal_border_color       "#484848"
bspc config top_padding				  6
bspc config bottom_padding            0
bspc config left_padding              0
bspc config right_padding             0
bspc config window_gap				  12
bspc config split_ratio				  0.52
bspc config borderless_monocle		  false
bspc config gapless_monocle			  false
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true

# Bar
bspc rule -a "Polybar" state=sticky border=off
bspc rule -a "Plank" layer=above manage=on border=off

# Floating applications
bspc rule -a "stacer" desktop='^1' state=floating center=on follow=on focus=on border=off
bspc rule -a "Lxappearance" desktop='^1' state=floating center=on follow=on focus=on
bspc rule -a "Blueman-manager" desktop='^1' state=floating center=on follow=on focus=on
bspc rule -a "Nvidia-settings" desktop='^1' center=on state=floating
bspc rule -a "Pavucontrol" desktop='^1' center=on state=floating
bspc rule -a "Transmission-gtk" desktop='^1' state=floating center=on follow=on focus=on
bspc rule -a "Nm-connection-editor" desktop='^1' state=floating center=on follow=on focus=on
bspc rule -a "Org.gnome.Nautilus" desktop='^1' state=floating center=on follow=on focus=on
bspc rule -a "obs" desktop='^1' state=floating center=on follow=on focus=on
bspc rule -a "xpad" desktop='^1' sticky=on state=floating
bspc rule -a "Pamac-manager" desktop='^1' center=on state=floating
bspc rule -a "Sxiv" center=on state=floating
bspc rule -a "Java" center=on state=floating
bspc rule -a "Eclipse" center=on state=floating

# Fixed desktop applications
bspc rule -a "unimatrix" desktop='^1' state=fullscreen follow=on focus=on layer=above
bspc rule -a "st-256color" desktop='^2' follow=on focus=on
bspc rule -a "firefox" desktop='^3' state=monocle follow=on focus=on
bspc rule -a "firefox:Places" desktop='^3' state=floating follow=on focus=on
bspc rule -a "firefox:Popup" desktop='^3' state=floating border=off
bspc rule -a "Vlc" desktop='^4' follow=on
bspc rule -a "Steam" desktop='^5' state=floating follow=on border=off
bspc rule -a "vlc" desktop='^6' center=on follow=on state=floating
bspc rule -a "Wine" desktop='^7' follow=on focus=on state=floating border=off
bspc rule -a "Wine:leagueclient" desktop='^7' follow=on focus=on state=floating border=off
bspc rule -a "Wine:leagueclientux.exe" desktop='^7' follown=on focus=on state=floating border=off
bspc rule -a "Lutris" desktop='^7' state=floating center=on follow=on focus=on border=off

# fd1=$(bspc query -D -d '^5')
# bspc subscribe node | while read -a msg ; do
# 	desk_id=${msg[2]}
# 	wid=${msg[3]}
# 	if [ "$desk_id" = "$fd1" ]; then
# 		bspc node "$wid" -t floating
# 	fi
# done &

# Window dodge Plank
bspc subscribe desktop_focus | while read -a msg ; do
	bspc node -f north
done &

$XDG_CONFIG_HOME/bspwm/autostart.sh &!
