require('nvim-treesitter.configs').setup {
  ensure_installed = {
    "c",
    "cpp",
    "rust",
    "python",
    "lua",
    "comment",
    "json",
    "regex",
    "hcl",
    "bash",
    "html",
    "css",
    "yaml",
    "javascript",
    "markdown",
    "markdown_inline"
  },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = {"markdown"},
    disable = {
      "java",
      "kotlin",
      "nix",
      "dart",
      "rst",
      "fennel",
      "erlang",
      "ocaml",
      "ocaml_interface",
      "teal",
      "ocamllex",
      "clojure",
      "swift",
      "r",
      "c_sharp",
      "svelte",
      "tsx",
      "julia",
      "typescript",
      "gdscript",
      "ledger",
      "sparql",
      "query",
      "verilog",
      "scala",
      "supercollider",
      "go",
      "haskell",
      "jsdoc",
      "toml",
      "glimmer",
      "ruby",
      "ql",
      "elm",
      "jsonc",
      "vue",
      "graphql",
      "turtle",
      "php",
      "devicetree"
    }
  }
}
