[[language]]
name = "python"
language-servers = ["pylsp"]
# roots = ["pyproject.toml"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[language-server.pylsp.config.pylsp]
# https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#pylsp_mypy
plugins.ruff.enabled = true
plugins.black.enabled = true
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true

[[language]]
name="rust"
roots = ["Cargo.toml", "Cargo.lock"]
formatter = { command = "rustfmt" , args = ["+nightly"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "dprint", args = [ "fmt", "--stdin", "markdown" ] }
auto-format = true
