local tree_cb = require('nvim-tree.config').nvim_tree_callback
vim.g.nvim_tree_auto_ignore_ft = {'startify', 'dashboard'}
vim.g.nvim_tree_special_files = { 'README.md', 'Makefile', 'MAKEFILE', 'CMakeLists.txt' }
vim.g.nvim_tree_hide_dotfiles = 1
vim.g.nvim_tree_auto_open = 0
vim.g.nvim_tree_auto_close = 0
vim.g.nvim_tree_width = 25
vim.g.nvim_tree_bindings = {
  ["<CR>"] = tree_cb("edit"),
  ["o"] = tree_cb("edit"),
  ["<C-[>"] = tree_cb("dir_up"),
  ["<C-]>"] = tree_cb("cd"),
  ["<C-v>"] = tree_cb("vsplit"),
  ["<C-x>"] = tree_cb("split"),
  ["<C-t>"] = tree_cb("tabnew"),
  ["<"] = tree_cb("prev_sibling"),
  [">"] = tree_cb("next_sibling"),
  ["x"] = tree_cb("close_node"),
  ["<S-CR>"] = tree_cb("close_node"),
  ["<Tab>"] = tree_cb("preview"),
  ["I"] = tree_cb("toggle_ignored"),
  ["H"] = tree_cb("toggle_dotfiles"),
  ["R"] = tree_cb("refresh"),
  ["a"] = tree_cb("create"),
  ["d"] = tree_cb("remove"),
  ["r"] = tree_cb("rename"),
  ["<C-r>"] = tree_cb("full_rename"),
  ["-"] = tree_cb("cut"),
  ["c"] = tree_cb("copy"),
  ["p"] = tree_cb("paste"),
  ["y"] = tree_cb("copy_name"),
  ["Y"] = tree_cb("copy_path"),
  ["gy"] = tree_cb("copy_absolute_path"),
  ["[c"] = tree_cb("prev_git_item"),
  ["]c"] = tree_cb("next_git_item"),
  ["q"] = tree_cb("close")
}
